(function(){
'use strict';
const $=s=>document.querySelector(s);
const loader=$('#loader'), openBtn=$('#openBtn'), cover=$('#cover');
window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('loader-hidden'),250));
function effects(x,y){const fx=$('#tapFx');fx.style.left=x+'px';fx.style.top=y+'px';fx.classList.remove('ripple');void fx.offsetWidth;fx.classList.add('ripple');for(let i=0;i<5;i++){const s=document.createElement('span');s.className='spark';s.textContent=i%2?'✧':'✦';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',((Math.random()-.5)*110)+'px');s.style.setProperty('--y',((Math.random()-.5)*110)+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),1000)}}
function petals(n=9){for(let i=0;i<n;i++){const p=document.createElement('span');p.className='petal';p.textContent=i%3?'✿':'✧';p.style.left=Math.random()*100+'vw';p.style.top=(-20-Math.random()*50)+'px';p.style.setProperty('--x',((Math.random()-.5)*140)+'px');p.style.animationDuration=(5+Math.random()*4)+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),10000)}}
openBtn.addEventListener('click',e=>{e.stopPropagation();effects(e.clientX,e.clientY);document.body.classList.add('opened');setTimeout(()=>petals(12),300);setTimeout(()=>$('#details').scrollIntoView({behavior:'smooth',block:'start'}),1050)});
document.addEventListener('pointerdown',e=>{if(!document.body.classList.contains('opened')||e.target.closest('#scratchArea'))return;effects(e.clientX,e.clientY)},{passive:true});
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth',block:'start'})));
let area,canvas,ctx,ready=false,finished=false,drawing=false,last=null,raf=0;
function setupScratch(){if(finished)return;area=$('#scratchArea');canvas=$('#scratchCanvas');if(!area||!canvas)return;const r=area.getBoundingClientRect();if(r.width<20||r.height<20){setTimeout(setupScratch,300);return}const d=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.setTransform(d,0,0,d,0,0);ctx.globalCompositeOperation='source-over';const g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,'#b88339');g.addColorStop(.45,'#e5c47e');g.addColorStop(1,'#b57b34');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);for(let i=0;i<400;i++){ctx.fillStyle='rgba(255,255,255,'+(Math.random()*.12)+')';ctx.fillRect(Math.random()*r.width,Math.random()*r.height,1,1)}ready=true}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function erase(p){if(!ctx)return;ctx.save();ctx.globalCompositeOperation='destination-out';ctx.lineWidth=44;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(last){ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y)}else{ctx.arc(p.x,p.y,22,0,Math.PI*2)}ctx.stroke();ctx.restore();last=p;$('#scratchHint').style.opacity='.04';check()}
function check(){if(finished||raf)return;raf=requestAnimationFrame(()=>{raf=0;const d=ctx.getImageData(0,0,canvas.width,canvas.height).data;let clear=0,total=0;for(let i=3;i<d.length;i+=20){total++;if(d[i]<30)clear++}if(clear/total>.30){finished=true;$('#scratchHint').style.opacity='0';canvas.style.transition='opacity .45s';canvas.style.opacity='0';setTimeout(()=>{if(canvas.isConnected)canvas.remove();},500);petals(8)}})}
function bind(){if(!area)return;area.addEventListener('pointerdown',e=>{if(!ready||finished)return;e.preventDefault();drawing=true;last=null;if(area.setPointerCapture)area.setPointerCapture(e.pointerId);erase(point(e))},{passive:false});area.addEventListener('pointermove',e=>{if(!drawing||finished)return;e.preventDefault();erase(point(e))},{passive:false});area.addEventListener('pointerup',()=>{drawing=false;last=null});area.addEventListener('pointercancel',()=>{drawing=false;last=null})}
setTimeout(()=>{setupScratch();bind()},100);window.addEventListener('resize',()=>{if(!finished){setupScratch()}});
})();
