(function(){'use strict';
const $=s=>document.querySelector(s);
const cover=$('#cover'), loader=$('#loader'), invitation=$('#invitation');
window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('loader-hidden'),220));
function effects(x,y){const fx=$('#tapFx');if(!fx)return;fx.style.left=x+'px';fx.style.top=y+'px';fx.classList.remove('ripple');void fx.offsetWidth;fx.classList.add('ripple');for(let i=0;i<4;i++){const s=document.createElement('span');s.className='spark';s.textContent='✦';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',((Math.random()-.5)*100)+'px');s.style.setProperty('--y',((Math.random()-.5)*100)+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),950)}}
function petals(n=12){for(let i=0;i<n;i++){const p=document.createElement('span');p.className='petal';p.textContent=i%2?'✿':'✧';p.style.left=Math.random()*100+'vw';p.style.top=(-20-Math.random()*50)+'px';p.style.setProperty('--x',((Math.random()-.5)*120)+'px');p.style.animationDuration=(5+Math.random()*4)+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),10000)}}
function openInvitation(e){if(document.body.classList.contains('opened'))return;if(e){e.preventDefault();effects(e.clientX||innerWidth/2,e.clientY||innerHeight/2)}document.body.classList.add('opened');invitation.setAttribute('aria-hidden','false');setTimeout(()=>petals(12),250);setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),500)}
cover.addEventListener('pointerup',openInvitation);cover.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){openInvitation(e)}});

document.addEventListener('pointerdown',e=>{if(document.body.classList.contains('opened')&&!e.target.closest('#scratchArea'))effects(e.clientX,e.clientY)},{passive:true});

const area=$('#scratchArea'),canvas=$('#scratchCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let drawing=false,last=null,finished=false,raf=0;
function setupScratch(){if(finished)return;const r=area.getBoundingClientRect();if(r.width<20||r.height<20){setTimeout(setupScratch,200);return}const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0);const g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,'#b88339');g.addColorStop(.45,'#e8c87d');g.addColorStop(1,'#b67e35');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);for(let i=0;i<320;i++){ctx.fillStyle='rgba(255,255,255,'+(Math.random()*.14)+')';ctx.fillRect(Math.random()*r.width,Math.random()*r.height,1.5,1.5)}}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function erase(p){if(!ctx)return;ctx.save();ctx.globalCompositeOperation='destination-out';ctx.lineWidth=Math.max(48,area.clientWidth*.12);ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(last){ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke()}else{ctx.arc(p.x,p.y,ctx.lineWidth/2,0,Math.PI*2);ctx.fill()}ctx.restore();last=p;check()}
function check(){if(raf||finished)return;raf=requestAnimationFrame(()=>{raf=0;const d=ctx.getImageData(0,0,canvas.width,canvas.height).data;let clear=0,total=0;for(let i=3;i<d.length;i+=20){total++;if(d[i]<30)clear++}if(clear/total>.38){finished=true;area.classList.add('revealed');canvas.style.transition='opacity .45s';canvas.style.opacity='0';setTimeout(()=>canvas.remove(),500);petals(7)}})}
area.addEventListener('pointerdown',e=>{if(finished)return;e.preventDefault();drawing=true;last=null;area.setPointerCapture?.(e.pointerId);erase(point(e))},{passive:false});area.addEventListener('pointermove',e=>{if(!drawing||finished)return;e.preventDefault();erase(point(e))},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(ev=>area.addEventListener(ev,()=>{drawing=false;last=null}));
setTimeout(setupScratch,350);window.addEventListener('resize',()=>{if(!finished)setupScratch()});
})();
