(function(){'use strict';
const $=s=>document.querySelector(s), cover=$('#cover'), loader=$('#loader'), invitation=$('#invitation');
window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('loader-hidden'),300));
function effects(x,y){const fx=$('#tapFx');fx.style.left=x+'px';fx.style.top=y+'px';fx.classList.remove('ripple');void fx.offsetWidth;fx.classList.add('ripple');for(let i=0;i<24;i++){const s=document.createElement('span');s.className='spark';s.textContent=i%3===0?'✦':(i%2?'·':'❦');s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',((Math.random()-.5)*220)+'px');s.style.setProperty('--y',((Math.random()-.5)*190)+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),1100)}}
function petals(n=60){for(let i=0;i<n;i++){const p=document.createElement('span');p.className='petal';p.textContent=i%3===0?'✿':(i%2?'❀':'✽');p.style.left=Math.random()*100+'vw';p.style.top=(-30-Math.random()*100)+'px';p.style.setProperty('--x',((Math.random()-.5)*220)+'px');p.style.animationDuration=(5+Math.random()*4)+'s';p.style.animationDelay=(Math.random()*1.3)+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),11000)}}
function openInvitation(e){if(document.body.classList.contains('opened'))return;e?.preventDefault();const x=e?.clientX||innerWidth/2,y=e?.clientY||innerHeight*.78;effects(x,y);petals(70);document.body.classList.add('opened');invitation.setAttribute('aria-hidden','false');setTimeout(()=>window.scrollTo({top:0,behavior:'instant'}),50)}
cover.addEventListener('pointerup',openInvitation);cover.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){openInvitation(e)}});

const area=document.querySelector('.scratch-wrap'),canvas=$('#scratchCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let drawing=false,last=null,finished=false,raf=0;
function setupScratch(){if(finished)return;const r=area.getBoundingClientRect();if(r.width<30||r.height<30){setTimeout(setupScratch,100);return}const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);ctx.globalCompositeOperation='source-over';const panel=new Image();panel.onload=()=>{if(finished)return;ctx.clearRect(0,0,r.width,r.height);ctx.drawImage(panel,0,0,r.width,r.height)};panel.src='assets/scratch_panel.png'}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function erase(p){ctx.save();ctx.globalCompositeOperation='destination-out';ctx.lineWidth=Math.max(48,area.clientWidth*.16);ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(last){ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke()}else{ctx.arc(p.x,p.y,ctx.lineWidth/2,0,Math.PI*2);ctx.fill()}ctx.restore();last=p;checkClear()}
function checkClear(){if(raf||finished)return;raf=requestAnimationFrame(()=>{raf=0;const d=ctx.getImageData(0,0,canvas.width,canvas.height).data;let clear=0,total=0;for(let i=3;i<d.length;i+=16){total++;if(d[i]<30)clear++}if(clear/total>.38){finished=true;area.classList.add('revealed');canvas.style.transition='opacity .7s ease';canvas.style.opacity='0';setTimeout(()=>canvas.remove(),750);petals(12)}})}
canvas.addEventListener('pointerdown',e=>{if(finished)return;e.preventDefault();drawing=true;last=null;canvas.setPointerCapture?.(e.pointerId);erase(point(e))},{passive:false});canvas.addEventListener('pointermove',e=>{if(!drawing||finished)return;e.preventDefault();erase(point(e))},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>{drawing=false;last=null}));
setTimeout(setupScratch,400);window.addEventListener('resize',()=>{if(!finished)setupScratch()});
})();
